import { Tool, tool } from "ai";
import z from "zod";
import { createXMCClient } from "../../base/sitecoreClient";

export function getComponentDetailsTool(
  accessToken: string,
  contextId: string
): Tool {
  return tool({
    description:
      "Retrieve the details of a specific component, including its ID, name, datasource options, template information, and field definitions. Useful for understanding component structure, datasource requirements, and configuration options.",
    inputSchema: z.object({
      componentId: z
        .string()
        .describe(
          "The unique identifier (GUID) of the component (e.g., '86a03271-dff4-470a-92bd-b68c67de2e25')."
        ),
    }),
    outputSchema: z.object({
      success: z
        .boolean()
        .describe(
          "Indicates whether the component details were successfully retrieved. If false, check the error field for details."
        ),
      data: z
        .any()
        .nullable()
        .describe(
          "The component details including id, name, datasourceTemplateId, datasourceLocations, datasourceTemplatePath, datasourceFields, datasourceAutoGenerated, datasourceRequired, and hasDynamicPlaceholder. Returns null if the operation failed or the component was not found."
        ),
      error: z
        .string()
        .optional()
        .describe(
          "Error message describing what went wrong if success is false. Common errors include invalid componentId, component not found, or permission issues."
        ),
    }),
    execute: async ({ componentId }) => {
      try {
        const xmcClient = await createXMCClient(accessToken);
        const result = await xmcClient.agent.componentsGetComponent({
          path: {
            componentId: componentId,
          },
          query: {
            sitecoreContextId: contextId,
          },
        });

        return {
          success: true,
          data: result?.data || null,
        };
      } catch (error) {
        console.error("[ComponentTool] Error fetching component details:", error);
        return {
          success: false,
          error:
            error instanceof Error
              ? error.message
              : "Failed to fetch component details",
          data: null,
        };
      }
    },
  });
}

// Combined export of all component tools
export const componentTools = {
  getComponentDetailsTool,
};

// Helper function to create all component tools initialized
export function createAllAgentsApiComponentsTools(
  accessToken: string,
  contextId: string
) {
  return {
    getComponentDetails: getComponentDetailsTool(accessToken, contextId),
  };
}

